"""empty message

Revision ID: aa6510fdf0c0
Revises: b358739d5ea0
Create Date: 2026-01-14 11:55:23.433146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6510fdf0c0'
down_revision = 'b358739d5ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('droids', schema=None) as batch_op:
        batch_op.drop_constraint('droids_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('planets_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_droids')
        batch_op.drop_column('favorite_planets')
        batch_op.drop_column('favorite_vehicles')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vehicles_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_vehicles', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('favorite_planets', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('favorite_droids', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planets_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('size',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('droids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('droids_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
