"""empty message

Revision ID: bc6372ac8a03
Revises: c4c5f05185bd
Create Date: 2026-01-12 13:08:45.069108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6372ac8a03'
down_revision = 'c4c5f05185bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles_id')

    op.drop_table('vehicles')
    # ### end Alembic commands ###
