"""empty message

Revision ID: c732380c14ca
Revises: bc6372ac8a03
Create Date: 2026-01-12 13:10:53.656774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c732380c14ca'
down_revision = 'bc6372ac8a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_vehicles_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicles_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_vehicles_id_fkey', 'vehicles', ['vehicles_id'], ['id'])

    # ### end Alembic commands ###
